### ISSUE TITLE
The image not found (404)

### ISSUE THREAD

**Issue by kvandake** [scaleflex/react-cloudimage-responsive#10]
<img width="1440" alt="Screenshot 2019-11-12 at 18 06 41" src="https://user-images.githubusercontent.com/16502104/68683155-60b5dd80-0577-11ea-8662-da40f1d126a1.png">

Dev information:
- Next.js: 9.1.2 (SSR)
- React: 16.11.0
- react-cloudimage-responsive: 1.6.7

**Comment by dzmitry-stramavus** [comment]
hey @kvandake,

looks like you are trying to work with local images.

in the description of the plugin:

> NOTE: Your original (master) images should be stored on a server or storage bucket (S3, Google Cloud, Azure Blob...) reachable over HTTP or HTTPS by Cloudimage. If you want to upload your master images to Cloudimage, contact us at hello@cloudimage.io.
