### ISSUE TITLE
Problem with plugin install

### ISSUE THREAD

**Issue by laurage** [scaleflex/react-cloudimage-responsive#11]
Hello, 

I have just installed react-cloudimage-responsive with npm but I get this error:

`client.js:196 ./node_modules/react-cloudimage-responsive/dist/polyfills.jsModule not found: Error: Can't resolve 'core-js/es/math/trunc' in '/Users/me/Documents/code/projects/sanity-gatsby-portfolio/web/node_modules/react-cloudimage-responsive/dist'./node_modules/react-cloudimage-responsive/dist/polyfills.jsModule not found: Error: Can't resolve 'core-js/features/array/find' in '/Users/me/Documents/code/projects/sanity-gatsby-portfolio/web/node_modules/react-cloudimage-responsive/dist'./node_modules/react-cloudimage-responsive/dist/polyfills.jsModule not found: Error: Can't resolve 'core-js/features/array/for-each' in '/Users/me/Documents/code/projects/sanity-gatsby-portfolio/web/node_modules/react-cloudimage-responsive/dist'`

This is what I got from the terminal upon install:
`
> core-js@3.6.4 postinstall /Users/me/Documents/code/projects/sanity-gatsby-portfolio/web/node_modules/react-cloudimage-responsive/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

+ react-cloudimage-responsive@1.6.10
added 4 packages from 4 contributors and audited 23377 packages in 21.045s
found 8 vulnerabilities (2 low, 2 moderate, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
`

I am using React 16.8.6.

Any idea of how to solve this? Thanks!

**Comment by dzmitry-stramavus** [comment]
hey @laurage ,

try to install ```npm i core-js``` manually.

It should be installed automatically

**Comment by laurage** [comment]
This solved my problem, thanks!

**Comment by laurage** [comment]
Hi, I thought this solved my problem for a minute but it didn't, I still get the same error. I tried with the latest core-js version (3.6.4) and also the one I think you use (3.0.0), no success.
Any other idea?

**Comment by dzmitry-stramavus** [comment]
ok, try to remove node_modules and package-lock.json. And run ```npm install```

**Comment by laurage** [comment]
Hello,
Sadly it's still bringing the same errors when doing this.

**Comment by dzmitry-stramavus** [comment]
I'm closing the issue since nobody can reproduce the problem
