### ISSUE TITLE
lazyLoading no longer working

### ISSUE THREAD

**Issue by shoobzy** [scaleflex/react-cloudimage-responsive#12]
Hi

Just updated to version 3.0.3 (from v1.6) and it appears that lazyLoaded images are no longer lazy loading?

This is evident in the codesandbox example when viewing the Network tab in Chrome DevTools: https://codesandbox.io/s/react-cloudimage-responsive-example-q64n3

Thanks

**Comment by dzmitry-stramavus** [comment]
hey @shoobzy 

**fixed** in **3.0.8**

**Comment by shoobzy** [comment]
Great. Thanks @dzmitry-stramavus
