### ISSUE TITLE
babel-loader conflict with the latest react-scripts 

### ISSUE THREAD

**Issue by vladi-strilets** [scaleflex/react-cloudimage-responsive#13]
Hi, I have installed your react library, but I'm getting the version conflict for `babel-loader` from your dependencies (v7.x.x) and react-scripts dependencies (v8.x.x), so I can't run the app. 

Please update the dependencies, thanks!

**Comment by dzmitry-stramavus** [comment]
@vladi-strilets , hey

updated in **v3.1.0**
