### ISSUE TITLE
Is there an onerror event?

### ISSUE THREAD

**Issue by dartmoordunbar** [scaleflex/react-cloudimage-responsive#17]
Is there any way to detect the image failed to load or loaded the placeholder image? I'd like to fire off a function when this happens to rebuild the image.

**Comment by dzmitry-stramavus** [comment]
hey @dartmoordunbar ,

yes, it's possible. 

1. You need to configure your Filerobot container to return 404 if image missing
![image](https://user-images.githubusercontent.com/10708539/89436274-4bf12980-d746-11ea-9311-bf387fe0a150.png)

2. Just add onError handler to an image 
![image](https://user-images.githubusercontent.com/10708539/89436340-63c8ad80-d746-11ea-9ab3-a008e0393482.png)

codesandbox: https://codesandbox.io/s/react-cloudimage-responsive-example-umkmq?file=/src/index.js
