### ISSUE TITLE
Allow unmounting the provider

### ISSUE THREAD

**Issue by GregoryPotdevin** [scaleflex/react-cloudimage-responsive#18]
Due to lazy loading some components, we can't use a global provider for react-cloudimage-responsive are started wrapping a few lazy-loaded screens with the provider instead.
We are currently getting a memory leak warning from react when the component unmounts, as the resize handler isn't removed here : https://github.com/scaleflex/react-cloudimage-responsive/blob/master/src/provider.js

For our own needs we just subclassed the provider and added a componentWillUnmount method to remove the event listener.

```
class UnloadableCloudimageProvider extends CloudimageProvider {
  componentWillUnmount() {
    window.removeEventListener('resize', this.updateDimensions);
  }
}
```

This should probably be integrated natively into the library.

**Comment by dzmitry-stramavus** [comment]
@GregoryPotdevin hey, thx for posting the issue. We will update in next release

**Comment by dzmitry-stramavus** [comment]
done in v3.3.2
