### ISSUE TITLE
Usage as background image

### ISSUE THREAD

**Issue by ernest-okot** [scaleflex/react-cloudimage-responsive#4]
Is it possible to use this library to load a background image?

If so, how would I accomplish that? I would like a dynamically-resized background image.

**Comment by dzmitry-stramavus** [comment]
hey @ernest-okot ,

it's on our roadmap, will be done in next release. (js version of the plugin has this feature)

**Comment by dzmitry-stramavus** [comment]
**done in v1.6.0**

**doc**:  https://github.com/scaleflex/react-cloudimage-responsive#backgroundimg-component

**example**: https://codesandbox.io/s/react-cloudimage-responsive-background-1nin8
